[rospy.client][INFO] 2022-01-08 13:47:19,354: init_node, name[/show_robots_34098_1641629839327], pid[34098]
[xmlrpc][INFO] 2022-01-08 13:47:19,355: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-01-08 13:47:19,355: Started XML-RPC server [http://prajwal-IdeaPad-L340-15IRH-Gaming:38231/]
[rospy.impl.masterslave][INFO] 2022-01-08 13:47:19,355: _ready: http://prajwal-IdeaPad-L340-15IRH-Gaming:38231/
[rospy.init][INFO] 2022-01-08 13:47:19,355: ROS Slave URI: [http://prajwal-IdeaPad-L340-15IRH-Gaming:38231/]
[rospy.registration][INFO] 2022-01-08 13:47:19,356: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-01-08 13:47:19,356: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-01-08 13:47:19,456: registered with master
[rospy.rosout][INFO] 2022-01-08 13:47:19,456: initializing /rosout core topic
[rospy.rosout][INFO] 2022-01-08 13:47:19,462: connected to core topic /rosout
[rospy.simtime][INFO] 2022-01-08 13:47:19,463: initializing /clock core topic
[rospy.simtime][INFO] 2022-01-08 13:47:19,466: connected to core topic /clock
[rospy.internal][INFO] 2022-01-08 13:47:19,468: topic[/clock] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:45613/], count 0
[rospy.internal][INFO] 2022-01-08 13:47:19,478: topic[/grid3/allRobots/poses] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:35871/], count 0
[rospy.internal][INFO] 2022-01-08 13:47:19,735: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-01-08 13:47:19,735: topic[/grid3/displayrobot] adding connection to [/rviz], count 0
[rosout][ERROR] 2022-01-08 13:47:19,814: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:19,914: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,018: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,116: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,217: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,317: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,417: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,518: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,618: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,719: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,821: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:20,922: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:21,021: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rosout][ERROR] 2022-01-08 13:47:21,122: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7fec03030f70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 59, in botPosesSubscriberCb
    self.markersPublisher.publish(self.robotMarkers)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/visualization_msgs/msg/_MarkerArray.py", line 190, in serialize
    buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
AttributeError: 'numpy.ndarray' object has no attribute 'x'

[rospy.core][INFO] 2022-01-08 13:47:21,187: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-01-08 13:47:21,190: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-01-08 13:47:21,190: topic[/grid3/displayrobot] removing connection to /rviz
[rospy.internal][INFO] 2022-01-08 13:47:21,190: topic[/clock] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:45613/
[rospy.internal][INFO] 2022-01-08 13:47:21,190: topic[/grid3/allRobots/poses] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:35871/
[rospy.impl.masterslave][INFO] 2022-01-08 13:47:21,191: signal-2
[rospy.internal][WARNING] 2022-01-08 13:47:21,191: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:43597 (http://prajwal-IdeaPad-L340-15IRH-Gaming:45613/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2022-01-08 13:47:21,788: signal_shutdown [atexit]
