[rospy.client][INFO] 2022-01-08 13:38:44,244: init_node, name[/show_robots_33222_1641629324217], pid[33222]
[xmlrpc][INFO] 2022-01-08 13:38:44,244: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-01-08 13:38:44,244: Started XML-RPC server [http://prajwal-IdeaPad-L340-15IRH-Gaming:38845/]
[rospy.init][INFO] 2022-01-08 13:38:44,244: ROS Slave URI: [http://prajwal-IdeaPad-L340-15IRH-Gaming:38845/]
[rospy.impl.masterslave][INFO] 2022-01-08 13:38:44,244: _ready: http://prajwal-IdeaPad-L340-15IRH-Gaming:38845/
[rospy.registration][INFO] 2022-01-08 13:38:44,245: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-01-08 13:38:44,245: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-01-08 13:38:44,346: registered with master
[rospy.rosout][INFO] 2022-01-08 13:38:44,346: initializing /rosout core topic
[rospy.rosout][INFO] 2022-01-08 13:38:44,351: connected to core topic /rosout
[rospy.simtime][INFO] 2022-01-08 13:38:44,352: initializing /clock core topic
[rospy.simtime][INFO] 2022-01-08 13:38:44,354: connected to core topic /clock
[rospy.internal][INFO] 2022-01-08 13:38:44,356: topic[/clock] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:45613/], count 0
[rospy.internal][INFO] 2022-01-08 13:38:44,363: topic[/grid3/allRobots/poses] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:35871/], count 0
[rosout][ERROR] 2022-01-08 13:38:44,457: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rospy.internal][INFO] 2022-01-08 13:38:44,529: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2022-01-08 13:38:44,557: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rospy.internal][INFO] 2022-01-08 13:38:44,631: topic[/grid3/displayrobot] adding connection to [/rviz], count 0
[rosout][ERROR] 2022-01-08 13:38:44,658: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:44,758: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:44,857: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:44,958: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:45,059: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:45,159: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:45,260: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:45,361: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:45,461: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:45,562: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:45,663: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rosout][ERROR] 2022-01-08 13:38:45,763: bad callback: <bound method robotVisualizer.botPosesSubscriberCb of <__main__.robotVisualizer object at 0x7f38be723ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/prajwal/Documents/catkin/src/grid3/scripts/visualize_robots.py", line 54, in botPosesSubscriberCb
    self.robotMarkers.markers[i].orientation.z = self.data.thetas[i]
AttributeError: 'robotVisualizer' object has no attribute 'data'

[rospy.core][INFO] 2022-01-08 13:38:45,806: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-01-08 13:38:45,809: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-01-08 13:38:45,809: topic[/grid3/displayrobot] removing connection to /rviz
[rospy.internal][INFO] 2022-01-08 13:38:45,810: topic[/clock] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:45613/
[rospy.internal][INFO] 2022-01-08 13:38:45,810: topic[/grid3/allRobots/poses] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:35871/
[rospy.impl.masterslave][INFO] 2022-01-08 13:38:45,810: signal-2
[rospy.internal][WARNING] 2022-01-08 13:38:45,811: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:42047 (http://prajwal-IdeaPad-L340-15IRH-Gaming:35871/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2022-01-08 13:38:45,812: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:43597 (http://prajwal-IdeaPad-L340-15IRH-Gaming:45613/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2022-01-08 13:38:46,408: signal_shutdown [atexit]
